/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch design system — exact token values
        'tertiary-fixed': '#dbe1ff',
        'primary-fixed': '#ffdad4',
        surface: '#fff8f6',
        'error-container': '#ffdad6',
        'surface-variant': '#ffdad4',
        'tertiary-fixed-dim': '#b4c5ff',
        'on-tertiary-container': '#fefcff',
        'surface-container-high': '#ffe2dd',
        'inverse-surface': '#422a27',
        outline: '#956d67',
        'secondary-container': '#d9dff5',
        'inverse-primary': '#ffb4a8',
        secondary: '#575e70',
        primary: '#bc0100',
        'inverse-on-surface': '#ffedea',
        'surface-bright': '#fff8f6',
        'primary-container': '#eb0000',
        'on-primary': '#ffffff',
        'surface-container-highest': '#ffdad4',
        'on-secondary-fixed': '#141b2b',
        'outline-variant': '#ebbbb4',
        'on-tertiary-fixed-variant': '#003ea8',
        'on-primary-fixed-variant': '#930100',
        'secondary-fixed': '#dce2f7',
        'on-surface-variant': '#603e39',
        tertiary: '#0051d5',
        'on-primary-container': '#fffbff',
        'surface-container-low': '#fff0ee',
        'secondary-fixed-dim': '#c0c6db',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#404758',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#ffe9e6',
        'on-surface': '#2b1613',
        'on-background': '#2b1613',
        'surface-dim': '#f8d1cb',
        'on-tertiary-fixed': '#00174b',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#410000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#316bf3',
        'surface-tint': '#c00100',
        'on-secondary-container': '#5c6274',
        'on-error': '#ffffff',
        background: '#fff8f6',
        'primary-fixed-dim': '#ffb4a8',
        'on-error-container': '#93000a',
        // Dark mode surface tokens
        'dark-surface': '#1a0e0d',
        'dark-surface-container': '#2d1a18',
        'dark-on-surface': '#f5ddd9',
        'dark-on-surface-variant': '#d4a39c',
        'dark-outline-variant': '#5c3a35',
        'dark-surface-container-low': '#231310',
        'dark-surface-container-high': '#3d2320',
        'dark-surface-container-highest': '#4a2b28',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '64px',
        gutter: '24px',
        'container-max': '1200px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(40px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-ring': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.05)', opacity: '0.8' },
        },
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        shimmer: 'shimmer 2s infinite ease-in-out',
        'fade-in': 'fade-in 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-up': 'slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'pulse-ring': 'pulse-ring 2s ease-in-out infinite',
        'spin-slow': 'spin-slow 3s linear infinite',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
};
